#!/bin/sh

#ip -6 route del default
#ip -6 route add default via cccc:`echo "obase=16;$CLIENTROUTER"|bc`::2

#for i in $(seq 1 $CLIENTROUTERS)
#do		
#    if [ $i != $CLIENTROUTER ]
#    then
#        ip route add 172.26.$i.0/24 via 172.26.$CLIENTROUTER.2
#    fi 
#done

#for i in $(seq 1 $GATEWAYROUTERS)
#do
#    ip route add 172.25.$i.0/24 via 172.26.$CLIENTROUTER.2
#done

#ip route add 172.24.0.0/24 via 172.26.$CLIENTROUTER.2

ip route del default
ip route add default via 172.26.$CLIENTROUTER.2

tmp=$(mktemp)
jq --arg a "$GOSHIMMER" '.nodeconn.address = $a' /etc/wasp_config.json > "$tmp" && mv "$tmp" /etc/wasp_config.json

cd usr/bin
wasp -c /etc/wasp_config.json

# Keep Alive
#tail -f /var/log/dmesg

