#!/bin/sh

ip -6 route del default
ip -6 route add default via cccc:`echo "obase=16;$CLIENTROUTER"|bc`::2

tmp=$(mktemp)
jq --arg a "$GOSHIMMER" '.nodeconn.address = $a' /etc/wasp_config.json > "$tmp" && mv "$tmp" /etc/wasp_config.json
jq '.webapi.adminWhitelistDisabled = true' /etc/wasp_config.json > "$tmp" && mv "$tmp" /etc/wasp_config.json
cd usr/bin
wasp -c /etc/wasp_config.json

# Keep Alive
#tail -f /var/log/dmesg

