#!/bin/sh

sleep $(($DELAY * 3))

if [ 'gateways' = $ROUTE ]
  then
	for i in $(seq 1 $CLIENTROUTERS)
	do		
		ip route add 172.26.$(( $i )).0/24 via 172.24.0.$(( 1 + $GATEWAYROUTERS + $i ))
	done
fi

if [ 'clients' = $ROUTE ]
  then
  	for i in $(seq 1 $GATEWAYROUTERS)
	do
		ip route add 172.25.$(( $i )).0/24 via 172.24.0.$(( $i + 1 ))
	done
	for i in $(seq 1 $CLIENTROUTERS)
	do		
		if [ $i != $CLIENTROUTER ]
		then
			ip route add 172.26.$(( $i )).0/24 via 172.24.0.$(( 1 + $GATEWAYROUTERS + $i ))
		fi
	done
fi


echo
ip route
echo

# Keep Alive
tail -f /dev/null

